name: 🧪 Sürekli Entegrasyon (CI)


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
        python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest flake8
      - name: Lint
        run: flake8 . --max-line-length=120
      - name: Run tests
        run: pytest -q
